# Generated by Django 4.1.1 on 2022-10-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_created_on_post_create_on_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
