# Generated by Django 4.1.1 on 2022-10-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_create_on_post_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='create_on',
        ),
    ]
